print("change from remaster")
print('Hello from master flomaster')
print('Hello from feature')
print("Feature branch")
print("Feature branch 2")
print("practice-git")
print("change from practice branch")
print("GitHub push practice")
print("change from GitHub")
print("feature remote branch")
print("local conflict practice")
print("remote conflict practice")
print("change from developer A")
