print("change from conflict-practice")
print('Hello from master flomaster')
print('Hello from feature')
print("Feature branch")
print("Feature branch 2")
print("practice-git")
print("change from practice branch")